name: 'Setup AAPT2'
description: 'Downloads AAPT2 from Google Maven and adds it to PATH.'
author: 'OussamaTeyib'

branding:
  icon: 'package'
  color: 'green'

inputs:
  version:
    description: 'AAPT2 version to install. If not specified, uses the latest stable version.'
    required: false

runs:
  using: 'node24'
  main: 'dist/index.js'